apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-amqp" (include "core-broker.name" .) }}
  labels:
    app: {{ include "core-broker.name" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
      nodePort: 30082
  selector:
    app: {{ include "core-broker.name" . }}
