apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "core-broker.name" .) }}
  labels:
    app: {{ include "core-broker.name" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "core-broker.name" . }}
