apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "core-broker.name" . }}
  labels:
    app: {{ include "core-broker.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ printf "%s-headless" (include "core-broker.name" .) }}
  selector:
    matchLabels:
      app: {{ include "core-broker.name" . }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ include "core-broker.name" . }}
        dapr.io/app-port: {{ .Values.appPort | quote }}
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
      labels:
        app: {{ include "core-broker.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: amqp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: tkeelio/amqp:0.4.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
          env:
            - name: KEEL_PRIVATE_STORE
              value: {{ printf "%s-redis-private-store" .Values.middleware.name }}
            - name: KEEL_PUBLIC_STORE
              value: {{ printf "%s-redis-public-store" .Values.middleware.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.appPort}}
              protocol: TCP
          env:
            - name: KEEL_PRIVATE_STORE
              value: {{ printf "%s-redis-private-store" .Values.middleware.name }}
            - name: KEEL_PUBLIC_STORE
              value: {{ printf "%s-redis-public-store" .Values.middleware.name }}
            - name: DSN
              value: "root:a3fks=ixmeb82a@tcp(tkeel-core-broker-mysql:3306)/core_broker?charset=utf8mb4&parseTime=True&loc=Local"
            - name: TKEEL_TENANT_HOST
              valueFrom:
                configMapKeyRef:
                  name: tkeel-install-config
                  key:  TENANT_HOST
            - name: AMQP_SERVER
              value: "amqp://$(TKEEL_TENANT_HOST):30082"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
